apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-data
  namespace: fluss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-datalog
  namespace: fluss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi