apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: fluss
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888

          envFrom:
            - configMapRef:
                name: zookeeper-config

          volumeMounts:
            - name: zk-data
              mountPath: /data
            - name: zk-datalog
              mountPath: /datalog

          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 45
            periodSeconds: 20
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

  volumeClaimTemplates:
    - metadata:
        name: zk-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

    - metadata:
        name: zk-datalog
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi