FROM ghcr.io/apache/flink-kubernetes-operator:f504138

COPY  ./lib/ ./opt/flink/lib

COPY ./plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.1.jar /opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.1.jar