apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: bronze-ingest-event
  namespace: flink
spec:
  deploymentName: flink-session
  job:
    jarURI: s3://<flink-bucket>/job-artifacts/generate-fake-data-0.1.0.jar
    parallelism: 1
    args:
      [
      "--pipeline.name","bronze-ingest-event",
      "--entity","event",
      "--fluss.bootstrap.servers","coordinator-server-hs.fluss.svc.cluster.local:9123",
      "--sink.fluss.database","bronze",
      "--sink.fluss.table","event"
      ]

---

apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: bronze-ingest-customer
  namespace: flink
spec:
  deploymentName: flink-session
  job:
    jarURI: s3://<flink-bucket>/job-artifacts/generate-fake-data-0.1.0.jar
    parallelism: 1
    args:
      [
      "--pipeline.name","bronze-ingest-customer",
      "--entity","customer",
      "--fluss.bootstrap.servers","coordinator-server-hs.fluss.svc.cluster.local:9123",
      "--sink.fluss.database","bronze",
      "--sink.fluss.table","customer"
      ]

--- 
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: bronze-ingest-sale-order
  namespace: flink
spec:
  deploymentName: flink-session
  job:
    jarURI: s3://<flink-bucket>/job-artifacts/generate-fake-data-0.1.0.jar
    parallelism: 1
    args:
      [
      "--pipeline.name","bronze-ingest-sale-order",
      "--entity","sale_order",
      "--fluss.bootstrap.servers","coordinator-server-hs.fluss.svc.cluster.local:9123",
      "--sink.fluss.database","bronze",
      "--sink.fluss.table","sale_order"
      ]