services:
  # 1. Database backend
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=polaris
      - POSTGRES_PASSWORD=polaris
      - POSTGRES_DB=polaris_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polaris -d polaris_db"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      dynamic-lakehouse:

  # 2. Bootstrap polaris database schemas & objects for this realm
  polaris-bootstrap:
    image: apache/polaris-admin-tool:1.3.0-incubating
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/polaris_db
      QUARKUS_DATASOURCE_USERNAME: polaris
      QUARKUS_DATASOURCE_PASSWORD: polaris
      CLIENT_ID: root
      CLIENT_SECRET: s3cr3t
    command:
      - "bootstrap"
      - "--realm=POLARIS"
      - "--credential=POLARIS,root,s3cr3t"
    networks:
      dynamic-lakehouse:

  # 3. Polaris API 
  polaris:
    image: apache/polaris:1.3.0-incubating
    depends_on:
      polaris-bootstrap:
        condition: service_completed_successfully
    ports:
      # API port
      - "127.0.0.1:8181:8181"
      # Management port (metrics and health checks)
      - "127.0.0.1:8182:8182"
      # Optional, allows attaching a debugger to the Polaris JVM
      - "127.0.0.1:5005:5005"
    environment:
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"

      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      
      POLARIS_REALM_CONTEXT_REALMS: POLARIS
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      polaris.features.CLEANUP_ON_CATALOG_DROP: true
      polaris.features.DROP_WITH_PURGE_ENABLED: true # allow dropping tables from the SQL client

      QUARKUS_OTEL_SDK_DISABLED: true
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/polaris_db
      QUARKUS_DATASOURCE_USERNAME: polaris
      QUARKUS_DATASOURCE_PASSWORD: polaris
    
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s

    networks:
      dynamic-lakehouse:

networks:
  dynamic-lakehouse:
    name: dynamic-lakehouse
    external: true

volumes:
  postgres-data:
    name: "polaris-postgres-data"
