#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for fluss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: ""
  repository: "fluss-iceberg-s3"
  tag: "0.9.0"
  pullPolicy: IfNotPresent
  pullSecrets: []

# Fluss server configuration options
configurationOverrides:

  default.bucket.number: 1
  default.replication.factor: 1
  
  internal.listener.name: INTERNAL

  zookeeper.path.root: /fluss
  zookeeper.address: zookeeper.fluss.svc.cluster.local:2181  

  #remote.data.dir: 

  # s3.access-key: 
  # s3.secret-key: 
  s3.region: eu-north-1

  datalake.format: iceberg
  datalake.iceberg.name: dev_iceberg_datalake_catalog
  datalake.iceberg.warehouse: dev_iceberg_datalake_catalog
  datalake.iceberg.io-impl: org.apache.iceberg.aws.s3.S3FileIO
  datalake.iceberg.client.region: eu-north-1

  datalake.iceberg.type: rest
  datalake.iceberg.catalog.name : dev_iceberg_datalake_catalog
  datalake.iceberg.uri: http://polaris.polaris.svc.cluster.local:8181/api/catalog
  datalake.iceberg.rest.auth.type: OAUTH2
  datalake.iceberg.oauth2-server-uri: http://polaris.polaris.svc.cluster.local:8181/api/catalog/v1/oauth/tokens
  datalake.iceberg.header.X-Iceberg-Access-Delegation: vended-credentials
  datalake.iceberg.scope : PRINCIPAL_ROLE:ALL
  # datalake.iceberg.credential:

tablet:
  numberOfReplicas: 1
  storage:
    enabled: false
    size: 1Gi
    storageClass:

coordinator:
  numberOfReplicas: 1
  storage:
    enabled: false
    size: 1Gi
    storageClass:

# Fluss listener configurations
listeners:
  internal:
    port: 9123
  client:
    port: 9124

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # coordinatorServer:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  # tabletServer:
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi

serviceAccount:
  create: false
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Additional annotations to apply to the ServiceAccount.
  # These can be useful, for example, to support integrations like workload identity.
  annotations: {}
