FROM apache/fluss:0.9.0-incubating

COPY ./fluss-libs/iceberg-aws-1.10.1.jar /opt/fluss/plugins/iceberg/
COPY ./fluss-libs/iceberg-aws-bundle-1.10.1.jar /opt/fluss/plugins/iceberg/

COPY ./fluss-libs/fluss-fs-s3-0.9.0-incubating.jar /opt/fluss/plugins/s3/